# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "'t Kaaswinkeltje"
tagline: "Vers, eerlijk & lokaal"
email: your-email@example.com
description: >
  't Kaaswinkeltje is een begrip in Haarlem en omstreken. Geroemd sinds jaar en dag om zijn kwaliteit, service en beleving. Hier koopt de klant geen stukje kaas maar beleeft en wordt meegenomen in de mooiste verhalen van de beste en lekkerste Hollandse en Buitenlandse kazen. Beroemd is o.a. 'Het Neusje van Zalm', een heerlijke, romige en smeuïge Boeren Belegen kaas die wordt bereidt en gerijpt op een ambachtelijke en traditionele manier. Het 'Haarlems Zoetje' is een heerlijke oude kaas van Noord Hollandse melk uit de regio en bereidt volgens een eigen receptuur en manier van rijping.<br/><br/>Daardoor heeft de kaas een romige en nootachtige smaak. Heerlijk op de boterham, bij een goed glas wijn en geraspt over een heerlijke pasta of ovengerecht. Tijdens de frisse maanden van het jaar wordt onze eigen vers gemalen kaasfondue gretig afgenomen, bereidt met een heerlijk fris fruitige wijn of heerlijk lokaal Jopen biertje. Steeds bekender wordt ook 't Kaaswinkeltje met zijn meer dan vijftig soorten buitenlandse kaas zodat u van een heerlijk kaasplankje voor u zelf en uw gasten kunt genieten. Dit jaar bestaat ’t Kaaswinkeltje 85 jaar.
openingstijden: >
  maandag 13.00 - 17.30 uur<br/>
  dinsdag 09.30 - 17.30 uur<br/>
  woensdag 09.30 - 17.30 uur<br/>
  donderdag 09.30 - 17.30 uur<br/>
  vrijdag 09.30 -17.30 uur<br/>
  zaterdag 09.00 - 17.00 uur
phone: 023-5321082
address: >
  Koningstraat 56<br/> 2011 TD Haarlem
baseurl: "kaaswinkeltjehaarlem" # the subpath of your site, e.g. /blog
url: "//studioalloy.nl/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  kazen:
    output: true
    permalink: /kaas/:title/
